---
- name: Add InvalidDirectiveHere
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '^ServerRoot'
    line: 'InvalidDirectiveHere'
    state: present
  notify:
    - restart apache
