---
- name: Increase VM sockets after checking ServiceNow
  hosts: "{{ vm_name | default('localhost') }}"
  gather_facts: false

  vars:
    shadowman_cores: "increase"

  roles:
    - shadowman_cores_snow
