---
- name: Setup Path
  ansible.builtin.template:
    src: systemd.path.j2
    dest: /etc/systemd/system/{{ path_unit_name }}.path
    owner: root
    group: root
    mode: "0644"

- name: Setup Service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: "0644"

- name: Enable Path and Service and start
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - "{{ path_unit_name }}.path"
    - "{{ service_name }}.service"
