---
- name: Get playbook from Insights API
  ansible.builtin.uri:
    url: "https://console.redhat.com/api/remediations/v1/remediations/{{ pbs_per_host.results[my_idx | int].json.id }}/playbook"
    method: GET
    validate_certs: false
    status_code: 200
    return_content: true
    headers:
      Authorization: Bearer {{ token.json.access_token }}
      Content-Type: application/json
  register: playbook_content
  delegate_to: localhost
  when: pbs_per_host.results[my_idx | int].json.id is defined  # this is for when the remediation previously existed

- name: Write playbook content to file for upload to git
  ansible.builtin.copy:
    content: "{{ playbook_content.content | default('---') }}"
    dest: "/tmp/home/lightspeed/{{ insights_adv_target_host }}/{{ item | lower }}.yml"
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  when: pbs_per_host.results[my_idx | int].json.id is defined  # this is for when the remediation previously existed
