- name: Print out the total number of security CVEs with severity >= 3 for host "{{ insights_adv_target_host }}"
  ansible.builtin.debug:
    msg: "Detected {{ cve_list | unique | length }} security CVEs with severity >= 3 for host {{ insights_adv_target_host }}"
  delegate_to: localhost

- name: Create an incident in ServiceNow on CVE Issue
  servicenow.itsm.incident:
    state: new
    description: "{{ cve_list | unique | length }} CVEs with a severity >= 3 on {{ insights_adv_target_host }}. Remediation in progress by Ansible"
    short_description: "Detected {{ cve_list | unique | length }} CVEs with a severity >= 3 on host {{ insights_adv_target_host }}."
    caller: admin
    urgency: "high"
    impact: "high"
    other:
      u_vm_name: "{{ insights_adv_target_host }}"
      cmdb_ci: "{{ insights_adv_target_host | default(omit) }}"
  register: new_incident
  delegate_to: localhost

- name: Send notification message via Mattermost on CVE Issue
  community.general.mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_api_key }}"
    attachments:
      - text: "! ALERT !"
        color: '#ff00dd'
        title: "CVE Issue"
        fields:
          - title: Issue
            value: "CVE Issue Detected"
            short: true
          - title: Details
            value: "Detected {{ cve_list | unique | length }} CVEs with a severity >= 3 on host {{ insights_adv_target_host }}. ServiceNow Incident: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=incident.do?sysparm_query=number={{ new_incident.record.number }} has been created"
            short: true
  delegate_to: localhost

- name: Get Token from Service Account
  no_log: true
  ansible.builtin.uri:
    url: "{{ sso_endpoint }}"
    method: POST
    body:
      grant_type: client_credentials
      client_id: "{{ insights_auth_user }}"
      client_secret: "{{ insights_auth_password }}"
      scope: openid api.iam.service_accounts
    body_format: form-urlencoded
    status_code: 200
  register: token
  delegate_to: localhost

- name: Generate playbooks in Insights to remediate vulnerabilities
  ansible.builtin.uri:
    url: "{{ insights_api_url }}/remediations/v1/remediations"
    method: POST
    validate_certs: false
    status_code: 201
    return_content: true
    headers:
      Authorization: Bearer {{ token.json.access_token }}
      Content-Type: application/json
      accept: "text/vnd.yaml"
      Connection: "keep-alive"
    body_format: json
    body: "{{ lookup('ansible.builtin.template', 'templates/pb_generator_body.j2') }}"
  register: pbs_per_host
  loop: "{{ cve_list | unique }}"
  delegate_to: localhost

- name: Sync with Gitrepo
  ansible.builtin.git:
    repo: git@github.com:shadowman-lab/Ansible-Lightspeed-Remediation.git
    dest: /tmp/home/lightspeed
    version: main
    accept_newhostkey: true
    key_file: "{{ cert_key_file }}"
  delegate_to: localhost

- name: Pull playbooks into Git Repo
  ansible.builtin.include_tasks: git.yml
  loop: "{{ cve_list | unique }}"
  loop_control:
    index_var: my_idx

- name: Update git repo with backup
  ansible.builtin.shell: git add -A && git commit -m "Synching new playbooks" && git config --global core.sshCommand 'ssh -i {{ cert_key_file }} -F /dev/null'
    && git push
  args:
    chdir: /tmp/home/lightspeed
  environment:
    GIT_COMMITTER_NAME: "{{ git_name | default(omit) }}"
    GIT_COMMITTER_EMAIL: "{{ git_email | default(omit) }}"
    GIT_AUTHOR_NAME: "{{ git_name | default(omit) }}"
    GIT_AUTHOR_EMAIL: "{{ git_email | default(omit) }}"
  register: gitresult
  failed_when: gitresult.rc > 1
  changed_when: gitresult.rc == 0
  delegate_to: localhost

- name: Launch a project update from Red Hat Insights
  ansible.controller.project_update:
    project: "Red Hat Insights"
    timeout: 60
    validate_certs: false
  delegate_to: localhost

- name: Pass along pbs per host and incident data to the next role
  ansible.builtin.set_stats:
    data:
      pbs_per_host: "{{ pbs_per_host }}"
      new_incident: "{{ new_incident }}"
  delegate_to: localhost
