---
- name: Get VM info
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
      - "{{ inventory_hostname }}"
    vcenter_validate_certs: false
  register: vm_info
  delegate_to: localhost

- name: Collect id about a specific VM
  vmware.vmware_rest.vcenter_vm_info:
    vm: "{{ vm_info.value[0].vm }}"
    vcenter_validate_certs: false
  register: vm_full_info
  delegate_to: localhost

- name: Retrieve the CPU information from the VM
  vmware.vmware_rest.vcenter_vm_hardware_cpu_info:
    vm: '{{ vm_full_info.id }}'
    vcenter_validate_certs: false
  register: vm_cpu
  delegate_to: localhost

- name: Turn off VM
  vmware.vmware_rest.vcenter_vm_power:
    state: stop
    vm: '{{ vm_info.value[0].vm }}'
    vcenter_validate_certs: false
  delegate_to: localhost
  when: vm_cpu.value.count != cpu_cores

- name: Restore cores to the VM
  vmware.vmware_rest.vcenter_vm_hardware_cpu:
    vm: '{{ vm_full_info.id }}'
    count: '{{ cpu_cores }}'
    vcenter_validate_certs: false
  delegate_to: localhost
  when: vm_cpu.value.count != cpu_cores

- name: Turn on VM
  vmware.vmware_rest.vcenter_vm_power:
    state: start
    vm: '{{ vm_info.value[0].vm }}'
    vcenter_validate_certs: false
  delegate_to: localhost
  when: vm_cpu.value.count != cpu_cores
