---
- name: Get VM info
  vmware.vmware.guest_info:
    name: "{{ inventory_hostname }}"
    datacenter: "Shadowman-DC"
    validate_certs: false
  register: vm_info
  delegate_to: localhost

- name: Retrieve the CPU information from the VM
  vmware.vmware.vm_resource_info:
    moid: "{{ vm_info.guests[0].moid }}"
    validate_certs: false
  register: vm_resource
  delegate_to: localhost

- name: Turn off VM
  vmware.vmware.vm_powerstate:
    moid: "{{ vm_info.guests[0].moid }}"
    datacenter: "Shadowman-DC"
    state: powered-off
    validate_certs: false
  delegate_to: localhost
  when: vm_resource.vms[0].cpu.processor_count | int != cpu_cores | int

- name: Restore cores to the VM
  vmware.vmware.vm:
    moid: "{{ vm_info.guests[0].moid }}"
    datacenter: "Shadowman-DC"
    cpu:
      cores: "{{ cpu_cores }}"
    validate_certs: false
  delegate_to: localhost
  when: vm_resource.vms[0].cpu.processor_count | int != cpu_cores | int

- name: Turn on VM
  vmware.vmware.vm_powerstate:
    moid: "{{ vm_info.guests[0].moid }}"
    datacenter: "Shadowman-DC"
    state: powered-on
    validate_certs: false
  delegate_to: localhost
  when: vm_resource.vms[0].cpu.processor_count | int != cpu_cores | int
