- name: Create a list for each host with advisories
  ansible.builtin.set_fact:
    hosts_with_adv: "{{ hosts_with_adv | default([]) + [{'hostname': insights_adv_host_data.display_name,
                                    'insights_id': insights_adv_host_data.inventory_id,
                                    'advisory_id': item.payload.advisory_id,
                                    'advisory_name': item.payload.advisory_name,
                                    'advisory_type': item.payload.advisory_type}] }}"
  loop: "{{ insights_adv_data }}"
  delegate_to: localhost

- name: Get Token from Service Account
  no_log: true
  ansible.builtin.uri:
    url: "{{ sso_endpoint }}"
    method: POST
    body:
      grant_type: client_credentials
      client_id: "{{ insights_auth_user }}"
      client_secret: "{{ insights_auth_password }}"
      scope: openid api.iam.service_accounts
    body_format: form-urlencoded
    status_code: 200
  register: token
  delegate_to: localhost

- name: Create a list of advisories
  no_log: true
  ansible.builtin.uri:
    url: "{{ insights_api_url }}/patch/v3/advisories/{{ item.advisory_name }}"
    method: GET
    return_content: true
    headers:
      Authorization: Bearer {{ token.json.access_token }}
      Content-Type: application/json
    status_code: 200
  register: insights_cves
  loop: "{{ hosts_with_adv }}"
  delegate_to: localhost

- name: Create a list for each host with CVEs
  ansible.builtin.set_fact:
    hosts_with_cve: "{{ hosts_with_cve | default([]) + [{'hostname': insights_adv_host_data.display_name,
                                    'insights_id': insights_adv_host_data.inventory_id,
                                    'advisory_id': item.json.data.id,
                                    'cves': item.json.data.attributes.cves,
                                    'advisory_type_name': item.json.data.attributes.advisory_type_name,
                                    'severity': item.json.data.attributes.severity,
                                    'description': item.json.data.attributes.description}] }}"
  loop: "{{ insights_cves.results }}"
  delegate_to: localhost
  when:
    - item.json.data.attributes.cves is not none
    - item.json.data.attributes.cves | length > 0

- name: Create a list of security CVEs with severity >= 3
  ansible.builtin.set_fact:
    cve_list: "{{ cve_list | default([]) + item.cves }}"
  loop: "{{ hosts_with_cve | default([]) }}"
  delegate_to: localhost
  when:
    - item.severity | int >= 3
    - item.advisory_type_name == 'security'
    - hosts_with_cve is defined

- name: Pass along all CVEs with severity >= 3 for host "{{ insights_adv_target_host }}"
  ansible.builtin.set_stats:
    data:
      cvelist: "{{ cve_list | unique }}"
  delegate_to: localhost
  when:
    - cve_list is defined
    - hosts_with_cve is defined
